apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - destination-rule.yaml
  - virtual-service.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - services-preview.yaml
  - jenkins-rbac.yaml
