apiVersion: v1
kind: Secret
metadata:
  name: dame-secrets
  namespace: dame
  labels:
    app.kubernetes.io/name: dame
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DB_PASSWORD: "dame_secure_pass_2024"
