apiVersion: v1
kind: Service
metadata:
  name: dame
  namespace: dame
  labels:
    app.kubernetes.io/name: dame
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dame
