apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dame
# Image transformer - Argo CD Image Updater will modify newTag
images:
  - name: ghcr.io/oseitutu90/dame
    newTag: 69e9475c
